name: fitness
description: A new flutter plugin project.
version: 0.0.1
author: Juyoung, Lee <dev.juyoung@gmail.com>
homepage: https://github.com/dev-juyoung/Fitness

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.juyoung.fitness
        pluginClass: FitnessPlugin
      ios:
        pluginClass: FitnessPlugin
