name: fitness
description: Flutter plugin for reading step count data. Wraps HealthKit on iOS and GoogleFit on Android.
version: 0.1.0
homepage: https://github.com/dev-juyoung/Fitness

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.juyoung.fitness
        pluginClass: FitnessPlugin
      ios:
        pluginClass: FitnessPlugin
